name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]  # change if you deploy from a different branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: |
          cd maren-website/maren-website
          npm ci
      - name: Build
        run: |
          cd maren-website/maren-website
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: maren-website/maren-website/dist
          publish_branch: gh-pages